[versions]
activityKtx = "1.11.0"
agp = "8.13.1"
appUpdate = "2.1.0"
assetDelivery = "2.3.0"
constraintlayout = "2.2.1"
dotsindicator = "5.1.0"
fastadapter = "5.7.0"
firebaseAnalyticsKtx = "22.5.0"
firebaseCrashlytics = "20.0.3"
firebaseCrashlyticsGradle = "3.0.6"
googleServices = "4.4.4"
gradle = "8.13.1"
jsr305 = "3.0.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinGradlePlugin = "2.2.10"
kotlinReflect = "2.2.10"
lifecycleViewmodelKtx = "2.9.4"
lottie = "6.7.1"
material = "1.13.0"
materialdatetimepicker = "4.2.3"
navigationFragmentKtx = "2.9.6"
permissions = "0.5.0"
playServicesTasks = "18.4.0"
preferenceKtx = "1.2.1"
recyclerview = "1.4.0"
review = "2.0.2"
roomKtx = "2.8.3"
timber = "5.0.1"
activity = "1.11.0"
core = "1.17.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-dynamic-features-fragment = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigationFragmentKtx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
app-update = { module = "com.google.android.play:app-update", version.ref = "appUpdate" }
asset-delivery = { module = "com.google.android.play:asset-delivery", version.ref = "assetDelivery" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
fastadapter = { module = "com.mikepenz:fastadapter", version.ref = "fastadapter" }
fastadapter-extensions-binding = { module = "com.mikepenz:fastadapter-extensions-binding", version.ref = "fastadapter" }
fastadapter-extensions-expandable = { module = "com.mikepenz:fastadapter-extensions-expandable", version.ref = "fastadapter" }
fastadapter-extensions-utils = { module = "com.mikepenz:fastadapter-extensions-utils", version.ref = "fastadapter" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebaseAnalyticsKtx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics", version.ref = "firebaseCrashlytics" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsGradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServices" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
materialdatetimepicker = { module = "com.wdullaer:materialdatetimepicker", version.ref = "materialdatetimepicker" }
permissions = { module = "com.github.lorenzofelletti:permissions", version.ref = "permissions" }
play-services-tasks = { module = "com.google.android.gms:play-services-tasks", version.ref = "playServicesTasks" }
review = { module = "com.google.android.play:review", version.ref = "review" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

